const sequelize = require("../../db");
const { DataTypes } = require("sequelize");

const PlFormularz = sequelize.define("plformularz", {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  lokal: { type: DataTypes.STRING },
  adres: { type: DataTypes.STRING },
  telefon: { type: DataTypes.STRING },
  telefon2: { type: DataTypes.STRING },
  telefon3: { type: DataTypes.STRING },
  telefon4: { type: DataTypes.STRING },
  e_mail: { type: DataTypes.STRING },
  miejscowosc: { type: DataTypes.STRING },
  woj: { type: DataTypes.STRING },
  powiat: { type: DataTypes.STRING },
  dzien: { type: DataTypes.STRING },
  dzien2: { type: DataTypes.STRING },
  dzien3: { type: DataTypes.STRING },
  dzien4: { type: DataTypes.STRING },
  koszt: { type: DataTypes.STRING },
  koszt2: { type: DataTypes.STRING },
  koszt3: { type: DataTypes.STRING },
  koszt4: { type: DataTypes.STRING },
  od: { type: DataTypes.STRING },
  od2: { type: DataTypes.STRING },
  od3: { type: DataTypes.STRING },
  od4: { type: DataTypes.STRING },
  do: { type: DataTypes.STRING },
  forma_platnosci: { type: DataTypes.STRING },
  ilosc_prezentacji: { type: DataTypes.STRING },
  ilosc_prezentacji2: { type: DataTypes.STRING },
  ilosc_prezentacji3: { type: DataTypes.STRING },
  potw: { type: DataTypes.STRING },
  godzina_prezentacji: { type: DataTypes.STRING },
  godzina_prezentacji2: { type: DataTypes.STRING },
  godzina_prezentacji3: { type: DataTypes.STRING },
  ilosc_sali: { type: DataTypes.STRING },
  ilosc_sali2: { type: DataTypes.STRING },
  ilosc_sali3: { type: DataTypes.STRING },
  parking: { type: DataTypes.STRING },
  uwagi: { type: DataTypes.STRING },
  rezerwujacy: { type: DataTypes.STRING },
  cena_poczatkowa: { type: DataTypes.STRING },
  cena_poczatkowa2: { type: DataTypes.STRING },
  cena_poczatkowa3: { type: DataTypes.STRING },
  ilosc_prezentacji4: { type: DataTypes.STRING },
  godzina_prezentacji4: { type: DataTypes.STRING },
  ilosc_sali4: { type: DataTypes.STRING },
  cena_poczatkowa4: { type: DataTypes.STRING },
  grupa_handlowa: { type: DataTypes.STRING },
  spolka: { type: DataTypes.STRING },
});

module.exports = {
  Formularz,
};
