const Router = require("express");
const router = new Router();
const userRouter = require("./userRouter");
const basesRouter = require("./basesRouter");
const citiesRouter = require("./citiesRouter");
const formularzRouter = require("./formularzRouter");
const logsRouter = require("./logsRouter");
const speakerTemplateRouter = require("./speakerTemplateRouter");
const regionsRouter = require("./trails/regionsRouter");
const citiesWithRegionsRouter = require("./trails/citiesWithRegionsRouter");
const callTemplatesRouter = require("./trails/callTemplatesRouter");
const contactStatusRouter = require("./trails/contactStatusRouter");
const planningPersonRouter = require("./trails/planningPersonRouter");
const presentationTimeRouter = require("./trails/presentationTimeRouter");
const projectConcentRouter = require("./trails/projectConcentRouter");
const projectSalesRouter = require("./trails/projectSalesRouter");
const regimentRouter = require("./trails/regimentRouter");
const reservationStatusRouter = require("./trails/reservationStatusRouter");
const formRouter = require("./trails/formRouter");
const trailsRouter = require("./trails/trailsRouter");

router.use("/user", userRouter);
router.use("/base", basesRouter);
router.use("/city", citiesRouter);
router.use("/formularz", formularzRouter);
router.use("/log", logsRouter);
router.use("/speakerTemplate", speakerTemplateRouter);
router.use("/region", regionsRouter);
router.use("/cityWithReg", citiesWithRegionsRouter);
router.use("/callTemplates", callTemplatesRouter);
router.use("/contactStatus", contactStatusRouter);
router.use("/planningPerson", planningPersonRouter);
router.use("/presentationTime", presentationTimeRouter);
router.use("/projectConcent", projectConcentRouter);
router.use("/projectSales", projectSalesRouter);
router.use("/regiment", regimentRouter);
router.use("/reservationStatus", reservationStatusRouter);
router.use("/form", formRouter);
router.use("/trail", trailsRouter);

module.exports = router;
