const sequelize = require("../../db");
const { DataTypes } = require("sequelize");

const Lists = sequelize.define("list", {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  present: { type: DataTypes.STRING },
  present_status: { type: DataTypes.INTEGER },
  full_name: { type: DataTypes.STRING },
  coupon_number: { type: DataTypes.STRING },
  telephone: { type: DataTypes.ARRAY(DataTypes.STRING) },
  guests: { type: DataTypes.INTEGER },
  couples: { type: DataTypes.INTEGER },
  passport: { type: DataTypes.INTEGER },
  age: { type: DataTypes.INTEGER },
  instead: { type: DataTypes.STRING },
  guest_full_name: { type: DataTypes.STRING },
  client_with_bank_refusal: { type: DataTypes.STRING },
  guest_telephone: { type: DataTypes.STRING },
  left_not_admitted: { type: DataTypes.STRING },
  reason_id: { type: DataTypes.INTEGER },
  reason: { type: DataTypes.STRING },
  sms: { type: DataTypes.INTEGER },
  notes: { type: DataTypes.STRING },
  presentation_number: { type: DataTypes.INTEGER },
  location: { type: DataTypes.STRING },
  time: { type: DataTypes.STRING },
  address: { type: DataTypes.STRING },
  team: { type: DataTypes.INTEGER },
  who_called: { type: DataTypes.STRING },
  id_for_base: { type: DataTypes.INTEGER, allowNull: false },
  relevance_status: { type: DataTypes.BOOLEAN },
});

const KzLists = sequelize.define("kzlist", {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  present: { type: DataTypes.STRING },
  present_status: { type: DataTypes.INTEGER },
  full_name: { type: DataTypes.STRING },
  coupon_number: { type: DataTypes.STRING },
  telephone: { type: DataTypes.ARRAY(DataTypes.STRING) },
  guests: { type: DataTypes.INTEGER },
  couples: { type: DataTypes.INTEGER },
  passport: { type: DataTypes.INTEGER },
  age: { type: DataTypes.INTEGER },
  instead: { type: DataTypes.STRING },
  guest_full_name: { type: DataTypes.STRING },
  client_with_bank_refusal: { type: DataTypes.STRING },
  guest_telephone: { type: DataTypes.STRING },
  left_not_admitted: { type: DataTypes.STRING },
  reason_id: { type: DataTypes.INTEGER },
  reason: { type: DataTypes.STRING },
  sms: { type: DataTypes.INTEGER },
  notes: { type: DataTypes.STRING },
  presentation_number: { type: DataTypes.INTEGER },
  location: { type: DataTypes.STRING },
  time: { type: DataTypes.STRING },
  address: { type: DataTypes.STRING },
  team: { type: DataTypes.INTEGER },
  who_called: { type: DataTypes.STRING },
  id_for_base: { type: DataTypes.INTEGER, allowNull: false },
  relevance_status: { type: DataTypes.BOOLEAN },
});

const PlLists = sequelize.define("pllist", {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  present: { type: DataTypes.STRING },
  present_status: { type: DataTypes.INTEGER },
  full_name: { type: DataTypes.STRING },
  coupon_number: { type: DataTypes.STRING },
  telephone: { type: DataTypes.ARRAY(DataTypes.STRING) },
  guests: { type: DataTypes.INTEGER },
  couples: { type: DataTypes.INTEGER },
  passport: { type: DataTypes.INTEGER },
  age: { type: DataTypes.INTEGER },
  instead: { type: DataTypes.STRING },
  guest_full_name: { type: DataTypes.STRING },
  client_with_bank_refusal: { type: DataTypes.STRING },
  guest_telephone: { type: DataTypes.STRING },
  left_not_admitted: { type: DataTypes.STRING },
  reason_id: { type: DataTypes.INTEGER },
  reason: { type: DataTypes.STRING },
  sms: { type: DataTypes.INTEGER },
  notes: { type: DataTypes.STRING },
  presentation_number: { type: DataTypes.INTEGER },
  location: { type: DataTypes.STRING },
  time: { type: DataTypes.STRING },
  address: { type: DataTypes.STRING },
  team: { type: DataTypes.INTEGER },
  who_called: { type: DataTypes.STRING },
  id_for_base: { type: DataTypes.INTEGER, allowNull: false },
  relevance_status: { type: DataTypes.BOOLEAN },
});

module.exports = {
  Lists,
  KzLists,
  PlLists,
};
